version: "3.8"

services:
  # Node.js Application
  app:
    image: mahmoudkamalaldeen/yalla_ecommerce_api:latest
    container_name: yalla_api_prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file:
      - config.env
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8000/test', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
